# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: e14b3e885adbc60c1fb88b6d5461f628bb7b355e7e68fea730a93cd717df28d27cc2643526eb64f5a3c8baa038b50f09341cd47f093b886fbaf275d134f1708e

test:
  secret_key_base: e6ff960239d9086759f4763bb4cc4b73d74fab1aa3d6fec770712094b9e76dc00eed38a3cd14ad64c911926370311819760ddd415e850932e0a14bae736388e1

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
